create table if not exists public.findings (
  id text primary key,
  scoring_version integer not null default 1,
  observed_at timestamptz not null,
  certificate_not_before text,
  registrable text not null,
  domains text[] not null default '{}',
  score integer not null,
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  signals jsonb not null default '[]'::jsonb,
  matched_brands text[] not null default '{}',
  matched_schemes text[] not null default '{}',
  issuer text,
  suppressed boolean not null default false,
  source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.findings add column if not exists scoring_version integer not null default 1;
create index if not exists findings_scoring_version_idx on public.findings (scoring_version);
create index if not exists findings_observed_at_idx on public.findings (observed_at desc);
create index if not exists findings_severity_idx on public.findings (severity);
create index if not exists findings_registrable_idx on public.findings (registrable);
create index if not exists findings_matched_brands_idx on public.findings using gin (matched_brands);
create index if not exists findings_matched_schemes_idx on public.findings using gin (matched_schemes);

alter table public.findings enable row level security;

revoke all on table public.findings from anon, authenticated;
grant select on table public.findings to anon;
grant select, insert, update on table public.findings to service_role;

create policy findings_public_read on public.findings
  for select to anon
  using (suppressed = false);

create table if not exists public.finding_sources (
  finding_id text not null references public.findings(id) on delete cascade,
  source text not null,
  source_ref text not null,
  observed_at timestamptz not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (finding_id, source, source_ref)
);

create index if not exists finding_sources_finding_id_idx on public.finding_sources (finding_id);
create index if not exists finding_sources_source_idx on public.finding_sources (source);
create index if not exists finding_sources_observed_at_idx on public.finding_sources (observed_at desc);

alter table public.finding_sources enable row level security;

revoke all on table public.finding_sources from anon, authenticated;
grant select, insert, update on table public.finding_sources to service_role;

create table if not exists public.ct_source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  label text not null,
  checked_at timestamptz not null,
  ok boolean not null default false,
  scanned_entries integer not null default 0,
  matched integer not null default 0,
  persisted integer not null default 0,
  duration_ms integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ct_source_runs_checked_at_idx on public.ct_source_runs (checked_at desc);
create index if not exists ct_source_runs_source_checked_at_idx on public.ct_source_runs (source, checked_at desc);

alter table public.ct_source_runs enable row level security;

revoke all on table public.ct_source_runs from anon, authenticated;
grant select on table public.ct_source_runs to anon;
grant select, insert on table public.ct_source_runs to service_role;
grant usage, select on sequence public.ct_source_runs_id_seq to service_role;

create policy source_runs_public_read on public.ct_source_runs
  for select to anon
  using (true);

create table if not exists public.ingest_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.ingest_state enable row level security;

revoke all on table public.ingest_state from anon, authenticated;
grant select on table public.ingest_state to anon;
grant select, insert, update on table public.ingest_state to service_role;

create policy ingest_state_public_read on public.ingest_state
  for select to anon
  using (key in ('ct_poll_status', 'ct_source_state'));
