create table if not exists public.findings (
  id text primary key,
  scoring_version integer not null default 1,
  observed_at timestamptz not null,
  certificate_not_before text,
  registrable text not null,
  domains text[] not null default '{}',
  score integer not null,
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  signals jsonb not null default '[]'::jsonb,
  matched_brands text[] not null default '{}',
  matched_schemes text[] not null default '{}',
  issuer text,
  suppressed boolean not null default false,
  source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.findings add column if not exists scoring_version integer not null default 1;
alter table public.findings add column if not exists cert_serial text;
alter table public.findings add column if not exists cert_issuer_dn_sha256 text;
alter table public.findings add column if not exists entry_types text[] not null default '{}';
alter table public.findings add column if not exists san_count integer default 0;
alter table public.findings add column if not exists is_wildcard boolean not null default false;

create index if not exists findings_scoring_version_idx on public.findings (scoring_version);
create index if not exists findings_observed_at_idx on public.findings (observed_at desc);
create index if not exists findings_severity_idx on public.findings (severity);
create index if not exists findings_registrable_idx on public.findings (registrable);
create index if not exists findings_matched_brands_idx on public.findings using gin (matched_brands);
create index if not exists findings_matched_schemes_idx on public.findings using gin (matched_schemes);
-- Identity is computed by the scorer and queried through findings_pkey (id).
-- Existing databases: apply index-cleanup.sql after reviewing current usage.


alter table public.findings enable row level security;

revoke all on table public.findings from anon, authenticated;
grant select on table public.findings to anon;
grant select, insert, update on table public.findings to service_role;

create policy findings_public_read on public.findings
  for select to anon
  using (suppressed = false);

create table if not exists public.finding_sources (
  finding_id text not null references public.findings(id) on delete cascade,
  source text not null,
  source_ref text not null,
  observed_at timestamptz not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (finding_id, source, source_ref)
);

-- finding_sources_pkey already supports finding_id equality lookups.
create index if not exists finding_sources_source_idx on public.finding_sources (source);
create index if not exists finding_sources_observed_at_idx on public.finding_sources (observed_at desc);

alter table public.finding_sources enable row level security;

revoke all on table public.finding_sources from anon, authenticated;
grant select, insert, update on table public.finding_sources to service_role;

create table if not exists public.ct_source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  label text not null,
  checked_at timestamptz not null,
  ok boolean not null default false,
  scanned_entries integer not null default 0,
  matched integer not null default 0,
  persisted integer not null default 0,
  duration_ms integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ct_source_runs_checked_at_idx on public.ct_source_runs (checked_at desc);
create index if not exists ct_source_runs_source_checked_at_idx on public.ct_source_runs (source, checked_at desc);

alter table public.ct_source_runs enable row level security;

revoke all on table public.ct_source_runs from anon, authenticated;
grant select on table public.ct_source_runs to anon;
grant select, insert on table public.ct_source_runs to service_role;
grant usage, select on sequence public.ct_source_runs_id_seq to service_role;

create policy source_runs_public_read on public.ct_source_runs
  for select to anon
  using (true);

create table if not exists public.ingest_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.ingest_state enable row level security;

revoke all on table public.ingest_state from anon, authenticated;
grant select on table public.ingest_state to anon;
grant select, insert, update on table public.ingest_state to service_role;

create policy ingest_state_public_read on public.ingest_state
  for select to anon
  using (key in ('ct_poll_status', 'ct_source_state', 'intel_poll_status'));

create table if not exists public.ct_logs (
  log_id            text primary key,          -- base64 SHA-256 of the log public key
  operator          text not null,
  description       text not null,
  protocol          text not null check (protocol in ('rfc6962', 'static-ct-api')),
  submission_url    text not null,
  monitoring_url    text not null,             -- static-ct-api only; equals submission_url for rfc6962
  public_key_der    text not null,             -- base64
  state             text not null,             -- qualified | usable | readonly | retired | rejected
  not_after_start   timestamptz,               -- temporal shard lower bound, null = unsharded
  not_after_limit   timestamptz,               -- temporal shard upper bound, null = unsharded
  refreshed_at      timestamptz not null default now()
);

create index if not exists ct_logs_protocol_state_idx on public.ct_logs (protocol, state);

alter table public.ct_logs enable row level security;
grant select on table public.ct_logs to anon;
grant select, insert, update, delete on table public.ct_logs to service_role;
create policy ct_logs_public_read on public.ct_logs for select to anon using (true);

create table if not exists public.ct_log_cursors (
  log_id            text primary key references public.ct_logs(log_id) on delete cascade,
  next_index        bigint not null default 0,
  tree_size         bigint not null default 0, -- from last checkpoint/STH
  last_advanced_at  timestamptz,
  last_error        text,
  last_error_at     timestamptz
);

alter table public.ct_log_cursors enable row level security;
grant select on table public.ct_log_cursors to anon;
grant select, insert, update on table public.ct_log_cursors to service_role;
create policy ct_log_cursors_public_read on public.ct_log_cursors for select to anon using (true);

create table if not exists public.source_health (
  id          bigserial primary key,
  source      text not null,             -- log_id, 'certstream', 'crtsh'
  protocol    text not null,             -- 'rfc6962' | 'static-ct-api' | 'websocket' | 'http'
  observed_at timestamptz not null default now(),
  status      text not null check (status in ('ok', 'degraded', 'failed', 'stale')),
  tree_size   bigint,
  next_index  bigint,
  lag_entries bigint,
  detail      jsonb not null default '{}'::jsonb
);

create index if not exists source_health_source_observed_at_idx
  on public.source_health (source, observed_at desc);

alter table public.source_health enable row level security;
revoke all on table public.source_health from anon, authenticated;
grant select on table public.source_health to anon;
grant select, insert on table public.source_health to service_role;
create policy source_health_public_read on public.source_health for select to anon using (true);

alter table public.findings add column if not exists enrichment jsonb not null default '{}'::jsonb;

create table if not exists public.domain_enrichments (
  domain      text primary key,
  enriched_at timestamptz not null default now(),
  dns         jsonb not null default '{}'::jsonb,
  http        jsonb not null default '{}'::jsonb,
  rdap        jsonb not null default '{}'::jsonb,
  live        boolean not null default false,
  details     jsonb not null default '{}'::jsonb
);

create index if not exists domain_enrichments_enriched_at_idx
  on public.domain_enrichments (enriched_at desc);

alter table public.domain_enrichments enable row level security;
revoke all on table public.domain_enrichments from anon, authenticated;
grant select on table public.domain_enrichments to anon;
grant select, insert, update on table public.domain_enrichments to service_role;
create policy domain_enrichments_public_read on public.domain_enrichments for select to anon using (true);

create table if not exists public.alert_log (
  registrable  text primary key,
  alerted_at   timestamptz not null default now()
);

alter table public.alert_log enable row level security;
revoke all on public.alert_log from anon, authenticated;
grant select, insert, update on public.alert_log to service_role;

create table if not exists public.triage_actions (
  id          bigint generated by default as identity primary key,
  finding_id  text not null,
  action      text not null check (action in ('false_positive')),
  actor       text not null default 'triage',
  created_at  timestamptz not null default now()
);

alter table public.triage_actions enable row level security;
revoke all on public.triage_actions from anon, authenticated;
grant select, insert on public.triage_actions to service_role;
grant usage, select on sequence public.triage_actions_id_seq to service_role;

create table if not exists public.captures (
  id              bigint generated by default as identity primary key,
  finding_id      text not null,
  captured_at     timestamptz not null default now(),
  http_status     integer,
  title           text,
  server          text,
  favicon_mmh3    text,
  cloaking_detected boolean not null default false,
  screenshot_url  text,
  detail          jsonb not null default '{}'
);

create index if not exists captures_finding_id_idx on public.captures (finding_id);
create index if not exists captures_captured_at_idx on public.captures (captured_at desc);

alter table public.captures enable row level security;
revoke all on public.captures from anon, authenticated;
grant select, insert on public.captures to service_role;
grant usage, select on sequence public.captures_id_seq to service_role;

create table if not exists public.intel_evidence (
  id text primary key,
  domain text not null check (
    length(domain) <= 253 and domain = lower(domain)
    and domain ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'
  ),
  source text not null check (source in ('openphish', 'urlscan', 'urlhaus', 'threatfox')),
  source_ref text not null check (
    (source = 'openphish' and source_ref ~ '^https://(www[.])?openphish[.]com(/|$)')
    or (source = 'urlscan' and source_ref ~ '^https://urlscan[.]io(/|$)')
    or (source = 'urlhaus' and source_ref ~ '^https://urlhaus[.]abuse[.]ch(/|$)')
    or (source = 'threatfox' and source_ref ~ '^https://threatfox[.]abuse[.]ch(/|$)')
  ),
  verdict text not null check (verdict in ('phishing', 'malware', 'observed')),
  observed_at timestamptz not null,
  expires_at timestamptz not null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists intel_evidence_domain_expires_idx on public.intel_evidence (domain, expires_at);
create index if not exists intel_evidence_expires_idx on public.intel_evidence (expires_at);
create index if not exists findings_intel_candidates_idx
  on public.findings (score desc, observed_at desc, id) where suppressed = false and score >= 60;
create index if not exists findings_intel_domains_idx
  on public.findings using gin (domains) where suppressed = false;
create index if not exists findings_intel_empty_domains_idx
  on public.findings (registrable) where suppressed = false and cardinality(domains) = 0;
create index if not exists findings_intel_registrable_score_idx
  on public.findings (registrable, score desc, observed_at desc, id)
  where suppressed = false and score >= 60;

alter table public.intel_evidence enable row level security;
revoke all on table public.intel_evidence from public, anon, authenticated;
grant select on table public.intel_evidence to anon;
grant select, insert, update, delete on table public.intel_evidence to service_role;

drop policy if exists intel_evidence_public_read on public.intel_evidence;
create policy intel_evidence_public_read on public.intel_evidence
  for select to anon
  using (
    expires_at > now()
    and exists (
      select 1 from public.findings f
      where f.suppressed = false
        and (
          f.domains @> array[intel_evidence.domain]
          or (cardinality(f.domains) = 0
            and f.registrable = intel_evidence.domain)
        )
    )
  );

-- Service polling chooses one CT finding per registrable before applying the limit.
create or replace function public.intel_candidate_findings(candidate_limit integer default 500)
returns setof public.findings
language sql stable security invoker set search_path = ''
as $$
  select f.*
  from (
    select candidate.id, candidate.score, candidate.observed_at,
      row_number() over (
        partition by candidate.score >= 70
        order by candidate.score desc, candidate.observed_at desc, candidate.id
      ) as bucket_rank
    from (
      select distinct on (finding.registrable)
        finding.id, finding.registrable, finding.score, finding.observed_at
      from public.findings finding
      where finding.suppressed = false and finding.score >= 60
      order by finding.registrable, finding.score desc, finding.observed_at desc, finding.id
    ) candidate
    order by bucket_rank, candidate.score desc, candidate.observed_at desc, candidate.id
    limit least(greatest(candidate_limit, 1), 1000)
  ) candidate
  join public.findings f on f.id = candidate.id
  order by candidate.bucket_rank, candidate.score desc, candidate.observed_at desc, candidate.id;
$$;
revoke all on function public.intel_candidate_findings(integer) from public, anon, authenticated;
grant execute on function public.intel_candidate_findings(integer) to service_role;

-- Hosts have already passed the shared evidence verdict filter in the read API.
create or replace function public.intel_findings_for_hosts(hosts text[], result_limit integer default 100)
returns setof public.findings
language sql stable security invoker set search_path = ''
as $$
  select f.*
  from public.findings f
  where f.suppressed = false and f.score >= 60
    and (f.domains && hosts
      or (cardinality(f.domains) = 0 and f.registrable = any(hosts)))
  order by f.score desc, f.observed_at desc, f.id
  limit least(greatest(result_limit, 1), 100);
$$;
revoke all on function public.intel_findings_for_hosts(text[], integer) from public, anon, authenticated;
grant execute on function public.intel_findings_for_hosts(text[], integer) to anon, service_role;
