-- supabase/workbench-review.sql
--
-- Private tables and RPC for the authenticated analyst review workflow (Task 9).
-- All tables private: no anon / authenticated direct access.
-- Only the service-role reviewer API (api/reviews.js) reads or writes these
-- tables after the server has verified the reviewer's Supabase access token
-- against the REVIEWER_USER_IDS allowlist.
--
-- Deploy: apply only after Task 7 capacity check passes.

-- ---------------------------------------------------------------------------
-- finding_reviews: one private row per finding
-- ---------------------------------------------------------------------------
create table if not exists public.finding_reviews (
  finding_id   text        not null primary key
                            references public.findings(id) on delete cascade,
  status       text        not null default 'new'
                            check (status in ('new', 'investigating', 'resolved')),
  disposition  text        not null default 'unassessed'
                            check (disposition in ('unassessed', 'false_positive', 'reported_phishing')),
  note         text        not null default ''
                            check (length(note) <= 2000),
  updated_at   timestamptz not null default now(),
  updated_by   uuid        not null,
  revision     bigint      not null default 1
);

alter table public.finding_reviews enable row level security;
revoke all on public.finding_reviews from public, anon, authenticated;
grant select, insert, update on public.finding_reviews to service_role;

-- ---------------------------------------------------------------------------
-- finding_review_events: private append-only audit trail
-- ---------------------------------------------------------------------------
create table if not exists public.finding_review_events (
  id              bigint      generated by default as identity primary key,
  finding_id      text        not null,
  request_uuid    text        not null,
  prior_status    text,
  new_status      text        not null,
  prior_disp      text,
  new_disp        text        not null,
  note_snapshot   text        not null default '',
  actor           uuid        not null,
  revision        bigint      not null,
  created_at      timestamptz not null default now()
);

-- Idempotency: one event per (finding_id, request_uuid) pair.  The pair
-- guarantees a retry on a different finding with the same UUID is still
-- correctly rejected as a duplicate — the UUID is client-generated and
-- must be globally unique for the retry semantics to hold.
create unique index if not exists finding_review_events_request_uuid_idx
  on public.finding_review_events (request_uuid);

create index if not exists finding_review_events_finding_id_idx
  on public.finding_review_events (finding_id, created_at desc);

alter table public.finding_review_events enable row level security;
revoke all on public.finding_review_events from public, anon, authenticated;
grant select, insert on public.finding_review_events to service_role;
grant usage, select on sequence public.finding_review_events_id_seq to service_role;

-- ---------------------------------------------------------------------------
-- RPC: upsert_finding_review
--
-- 1. Validates the parent finding exists and is not suppressed.
-- 2. Locks the parent finding row so concurrent first-writes cannot both
--    insert.  (finding_reviews has no row to lock yet, so we lock the
--    referenced parent to serialise the first insert; the finding row is
--    already unique on id.)
-- 3. Validates transitions and revision.
-- 4. Idempotency: identical (request_uuid, finding_id, actor, payload) retry
--    returns the previous review + no new event.  A UUID reuse with a
--    different payload raises idempotency_conflict.
-- 5. Writes finding_reviews + finding_review_events in the same transaction.
-- ---------------------------------------------------------------------------
create or replace function public.upsert_finding_review(
  p_finding_id   text,
  p_status       text,
  p_disposition  text,
  p_note         text,
  p_actor        uuid,
  p_revision     bigint,
  p_request_uuid text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_existing  public.finding_reviews%rowtype;
  v_prev_evt  public.finding_review_events%rowtype;
  v_new_rev   bigint;
  v_result    jsonb;
  v_locked_id text;
begin
  perform set_config('statement_timeout', '3s', true);

  -- Validate parent + acquire lock.  This serialises concurrent first-writes
  -- and rejects reviews for unknown findings.
  select f.id into v_locked_id
    from public.findings f
   where f.id = p_finding_id
   for update;
  if v_locked_id is null then
    raise exception 'finding_not_found' using errcode = 'P0001';
  end if;

  -- Enum + payload validation
  if p_status not in ('new','investigating','resolved') then
    raise exception 'invalid_status' using errcode = 'P0001';
  end if;
  if p_disposition not in ('unassessed','false_positive','reported_phishing') then
    raise exception 'invalid_disposition' using errcode = 'P0001';
  end if;
  if p_status = 'resolved' and p_disposition = 'unassessed' then
    raise exception 'disposition_required_for_resolved' using errcode = 'P0001';
  end if;
  if length(coalesce(p_note, '')) > 2000 then
    raise exception 'note_too_long' using errcode = 'P0001';
  end if;
  if p_actor is null then
    raise exception 'invalid_actor' using errcode = 'P0001';
  end if;
  if p_request_uuid is null or length(p_request_uuid) < 8 or length(p_request_uuid) > 64 then
    raise exception 'invalid_request_uuid' using errcode = 'P0001';
  end if;

  -- Idempotency probe: same request_uuid must map to same finding+actor+payload.
  select * into v_prev_evt
    from public.finding_review_events
   where request_uuid = p_request_uuid
   limit 1;
  if found then
    if v_prev_evt.finding_id <> p_finding_id
       or v_prev_evt.actor <> p_actor
       or v_prev_evt.new_status <> p_status
       or v_prev_evt.new_disp <> p_disposition
       or v_prev_evt.note_snapshot <> coalesce(p_note, '') then
      raise exception 'idempotency_conflict' using errcode = 'P0001';
    end if;
    -- Return immutable original response: reconstruct from the recorded event,
    -- not the current (possibly later-updated) finding_reviews row.
    return jsonb_build_object(
      'finding_id',  v_prev_evt.finding_id,
      'status',      v_prev_evt.new_status,
      'disposition', v_prev_evt.new_disp,
      'note',        v_prev_evt.note_snapshot,
      'updated_at',  v_prev_evt.created_at,
      'updated_by',  v_prev_evt.actor,
      'revision',    v_prev_evt.revision
    );
  end if;

  -- Load current review (parent already locked so this cannot race).
  select * into v_existing
    from public.finding_reviews
   where finding_id = p_finding_id
   for update;

  if found then
    if v_existing.revision <> p_revision then
      raise exception 'revision_conflict' using errcode = 'P0002';
    end if;
    if not (
      (v_existing.status = 'new'           and p_status in ('new','investigating','resolved'))
      or (v_existing.status = 'investigating' and p_status in ('investigating','resolved'))
      or (v_existing.status = 'resolved'   and p_status in ('investigating'))
    ) then
      raise exception 'invalid_transition' using errcode = 'P0001';
    end if;
    v_new_rev := v_existing.revision + 1;
    update public.finding_reviews
       set status      = p_status,
           disposition = p_disposition,
           note        = coalesce(p_note, ''),
           updated_at  = now(),
           updated_by  = p_actor,
           revision    = v_new_rev
     where finding_id = p_finding_id;
  else
    if p_status not in ('new','investigating') then
      raise exception 'invalid_initial_status' using errcode = 'P0001';
    end if;
    if p_revision <> 1 then
      raise exception 'revision_conflict' using errcode = 'P0002';
    end if;
    v_new_rev := 1;
    insert into public.finding_reviews
      (finding_id, status, disposition, note, updated_by, revision)
    values
      (p_finding_id, p_status, p_disposition, coalesce(p_note, ''), p_actor, v_new_rev);
  end if;

  insert into public.finding_review_events
    (finding_id, request_uuid, prior_status, new_status,
     prior_disp, new_disp, note_snapshot, actor, revision)
  values
    (p_finding_id, p_request_uuid,
     case when v_existing.finding_id is not null then v_existing.status      else null end,
     p_status,
     case when v_existing.finding_id is not null then v_existing.disposition else null end,
     p_disposition,
     coalesce(p_note, ''),
     p_actor,
     v_new_rev);

  select row_to_json(r.*)::jsonb into v_result
    from public.finding_reviews r
   where r.finding_id = p_finding_id;
  return coalesce(v_result, '{}'::jsonb);
end;
$$;

revoke all on function public.upsert_finding_review(text,text,text,text,uuid,bigint,text)
  from public, anon, authenticated;
grant execute on function public.upsert_finding_review(text,text,text,text,uuid,bigint,text)
  to service_role;

-- ---------------------------------------------------------------------------
-- RPC: list_finding_review_events
--
-- Paginated read of the private audit trail (50 default / 100 max).
-- Service-only.  No fetch-all.
-- ---------------------------------------------------------------------------
create or replace function public.list_finding_review_events(
  p_finding_id text,
  p_limit      integer default 50,
  p_before_id  bigint  default null
)
returns setof public.finding_review_events
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select *
    from public.finding_review_events
   where finding_id = p_finding_id
     and (p_before_id is null or id < p_before_id)
   order by id desc
   limit least(greatest(coalesce(p_limit, 50), 1), 100);
$$;

revoke all on function public.list_finding_review_events(text,integer,bigint)
  from public, anon, authenticated;
grant execute on function public.list_finding_review_events(text,integer,bigint)
  to service_role;
